### ISSUE TITLE
Always says mark is overwritten

### ISSUE THREAD

**Issue by mkleehammer** [liuyinz/binky-mode#11]
Small thing, but when `binky-overwrite` is true, setting a mark always results in the message "Mark <ch> is overwritten", even if the mark did not exist before.

Great package, thanks.

**Comment by eki3z** [comment]
fixed, please check it.

**Comment by mkleehammer** [comment]
That actually broke saving:

- mark a - nothing in echo area, good
- move and mark b - says mark a already exists and does not set mark b

You can now only set the first mark.

**Comment by eki3z** [comment]
@mkleehammer , whether two manual records are considerd as duplicated is determined by `binky-distance`. If you like, set it to 0, and then only marks on the same line are seen as duplicated.

https://github.com/liuyinz/binky.el/blob/a860fe2a557cdcdc5153d55ed3ab3c42bc4987aa/binky.el#L96

**Comment by mkleehammer** [comment]
It seems to be working now, but I really thought I tested it by trying to set the 2nd 'a' mark in a completely different buffer.

Anyway, there is a related behavior that makes it feel a bit off.  When it overwrites, it shows the message first, which has a delay, then pulses.  I know what it is doing, but it makes it feel broken or that the pulse came out of nowhere.

Swapping lines 935 & 936 fixes it.  Everywhere else the pulse happens before the message.

**Comment by eki3z** [comment]
Thankes for reporting experience! I adjust the order of message and highight, please test it again.

**Comment by mkleehammer** [comment]
Looks great.  Thanks for this package.  The jump display is great, especially the inclusion of the project.  I have two projects that share a ton of filenames, so that is helpful.
