### ISSUE TITLE
delete all binkies at once

### ISSUE THREAD

**Issue by fab6** [liuyinz/binky-mode#12]
Hi,
ometimes, I am collecting a few of these marks, but after a while I would like to have different ones.
Is there an option to delete all marks at once? Or do you have an idea, how to adjust it or overwriting th? S
Best Regards
Fab

**Comment by eki3z** [comment]
I would add a command to delete all records or records in a specific buffer-or-file after a while.

**Comment by fab6** [comment]
this sounds helpful, thank you
