### ISSUE TITLE
[Feature] save marks between sessions

### ISSUE THREAD

**Issue by younger-1** [liuyinz/binky-mode#7]
Enable marks in buffer available between sessions just like vim marks does.

**Comment by eki3z** [comment]
I guess bookmark would satisfy your need, maybe we could write a command to convert the marks to bookmarks for reusing next time. Or you could through `desktop-globals-to-save` to save and  restore it mannually.

Two methods:
1. conver the mark to bookmarks one by one
2. save the marks to file, give a name, and restore it from `M-x` manually next time
which method do you prefer?

**Comment by younger-1** [comment]
I think method 2 is more extensible and reliable. 
Emacs' `bookmark` is good enough in its own.

**Comment by eki3z** [comment]
Fine, I would add it to TODO list

**Comment by younger-1** [comment]
💪

**Comment by mkleehammer** [comment]
What about using Emacs' built-in savehist mode?  Enable and it add to `savehist-additional-variables`.  Obviously you shouldn't turn this on within the mode, but documenting it and which variable to add would make it work and take no code changes.

**Comment by eki3z** [comment]
I would implement it in the day or two

**Comment by eki3z** [comment]
@mkleehammer @younger-1 `binky-save-file` and `binky-read-file` already implemented. Try it.

**Comment by mkleehammer** [comment]
Works great.  Thanks.
